---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shellshock
  labels:
    name: shellshock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shellshock
    spec:
      containers:
        - image: vulnerables/cve-2014-6271
          imagePullPolicy: Always
          name: shellshock
          ports:
            - containerPort: 80
              hostPort: 50082
              name: http-port
          livenessProbe:
            httpGet:
              path: /
              port: http-port
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http-port
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
